---
name: Nuki Bridge
description: Virtual Nuki Bridge to use instead of the physical device
version: 0.0.10
slug: nuki_bridge
url: https://github.com/regevbr/RaspiNukiBridge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Bridge api port
host_dbus: true
image: ghcr.io/regevbr/nuki_bridge/{arch}
